export const AUTHOR_NAME = 'しゃもきっと'
export const BLOG_NAME = 'SK Sites'
// export const BLOG_DOMAIN = 'https://shamokit.com'
// export const BLOG_DOMAIN = 'http://localhost:3000'
export const BLOG_DOMAIN = ''
export const BLOG_DESCRIPTION = 'しゃもきっとの技術ブログ。主にフロントエンド周りの記事を書きます。'
export const DEFAULT_OGP_IMAGE = '/img/og-image01.jpg'
export const DEFAULT_OGP_IMAGE_CAT = '/img/og-image_cat01.jpg'
